version: '3'

services:
  # Node.js App Service
  test-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/test_db # Update this to connect to your DB
    ports:
      - '3001:3000' # Exposing app on a different port (3001) to avoid conflict
    volumes:
      - .:/app
    depends_on:
      - db

  # PostgreSQL Service
  db:
    image: postgres:15-alpine
    ports:
      - 5400:5432
    volumes:
      - postgresDB:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
      TZ: UTC
      PGTZ: UTC

volumes:
  postgresDB:
